sudo: false
language: ruby
rvm:
  - 2.5.9
  - 2.6.7
  - 2.7.3
  - 3.0.4
  - 3.1.2
gemfile:
  - gemfiles/sidekiq_4_0.gemfile
  - gemfiles/sidekiq_4_1.gemfile
  - gemfiles/sidekiq_4_2.gemfile
  - gemfiles/sidekiq_5_0.gemfile
  - gemfiles/sidekiq_5_1.gemfile
  - gemfiles/sidekiq_6_4.gemfile
services:
  - redis-server
cache: bundler
script:
  - "bundle exec rake spec"
  - "bundle exec rubocop -D"
notifications:
  email: false
